name: Build and upload release

on:
  push:
    tags:
      - 'v*'  # z. B. v1.0.0, v2.3.1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Wichtig für git describe

      - name: Get release tag
        id: get_tag
        run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Package plugin directory
        run: zip -r "octoprint_octolapse-${{ steps.get_tag.outputs.tag }}.zip" octoprint_octolapse/


      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "octoprint_octolapse-${{ steps.get_tag.outputs.tag }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
